"- literal de objeto definindo a __proto__, shorthand handler: handler, super chamada",
"- finally retornando o valor unico do bloco, try...catch",
"- acessa propriedade com notação de colchetes que nao seria acessivel com de ponto",
"- agregação de modulos",
"- alinhamento catch em promise",
"- aqui está o gerador de fibonacci usando next(x)para reiniciar a sequência:",
"- as eu uma importação de uma default",
"- as no export e import esses recursos renomeados",
"- carregamento dinamico de modulo import() com then e await",
"- construtor em uma classe",
"- construtor retornando valor diferente de new",
"- criar e acessar um objeto com uma propriedade que é outro objeto",
"- criar matrizes multidimensionais",
"- criar slots vazio em array com ,,",
"- declaração de função",
"- definir propriedade/metdo em prototype",
"- definir um get/set em um objeto literal",
"- definir um get/set posteriomente em um objeto ja criado",
"- definir um metodo em uma classe via this",
"- definir um metodo normal e abreviado em um objeto",
"- destruturação em for..of",
"- diferentes forma de criar matriz com comprimento diferente de zero, mas sem nenhum item",
"- do while",
"- encadear promise depois de um catch",
"- escopo de bloco",
"- escopo de função",
"- escopo de modulo",
"- escopo global",
"- estabelecendo a herança prototípica em um literal de objeto",
"- event handlers",
"- event listeners",
"- export multiplos item na ultima linha do arquivo",
"- export na frente do item, maneira mais facil",
"- export/import classe e usar-la em instanciação",
"- exportação padrao na mesma intrução, forma mais basica",
"- exportações nomeadas",
"- finally",
"- for",
"- ",
"- ",
"- herança em classe",
"- if...else",
"- if..else alinhado",
"- import com as",
"- import maneira mais simples multiplos item entre { }",
"- import todos os recursos com *",
"- importação de export default",
"- incorporar expressões em template string",
"- inicializar matriz 1/2/3 dimensões",
"- inicializar uma variavel",
"- instance field classe",
"- instance method classe",
"- instanciar um construtor",
"- instrução de bloco",
"- iteráveis definido no [Symbol.iterator]",
"- içamento de variação e função",
"- label",
"- literais RegExp",
"- literal bigint",
"- literal binario",
"- matriz dentro de uma matriz",
"- mixins",
"- mudar dimensão array com lenght",
"- notação de colchetes e notação normal",
"- objeto literal",
"- omitir construtor",
"- operador %",
"- operador **",
"- operador de descremento",
"- operador de incremento",
"- operador tenario",
"- os 2 acessador de objetos[. e colchetes]",
"- parametro padrão",
"- parametro rest",
"- parametro rest em contrutor de classe",
"- static block classe",
"- static field classe",
"- static method classe",
"- substituir toString aprimorado com super",
"- substituir um membros static de uma classe, mas aprimorado com super",
"- usar o resultado de uma promise, no caso, cadeia de promise",
"- usar recursos importados",
"- usar var antes de inicializar",
"- use de then em promisse, com suas duas funções",
"- uso de Reflect objeto",
"- uso de proxy objeto",
"- ",
"- "